// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_Practice.Models
{
    public partial class AssociationType
    {
        public AssociationType()
        {
            Friends = new HashSet<Friends>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Friends> Friends { get; set; }
    }
}