// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using EF_Practice.Models;

namespace EF_Practice.Models
{
    public partial class EfpracticedbContext
    {
        private EfpracticedbContextProcedures _procedures;

        public EfpracticedbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new EfpracticedbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public EfpracticedbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class EfpracticedbContextProcedures
    {
        private readonly EfpracticedbContext _context;

        public EfpracticedbContextProcedures(EfpracticedbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<GetFriendsResult>> GetFriendsAsync(string FirstName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "FirstName",
                    Size = 100,
                    Value = FirstName ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.NVarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<GetFriendsResult>("EXEC @returnValue = [dbo].[GetFriends] @FirstName", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
