// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EF_Practice.Models
{
    public partial class FamilyMembers
    {
        public int Id { get; set; }
        public string RoleInFamily { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public string EyeColor { get; set; }
        public string HairColor { get; set; }
        public string Gender { get; set; }
    }
}