// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF_Practice.Models
{
    public partial class GetFriendsResult
    {
        public string FriendName { get; set; }
    }
}
